[{
    "company_name":"hcl",
    "companyuser_id":"1",
    "date":ISODate("2020-09-25"),
    "students_appeared":"manickam,raja,ravikumar,raj"
},
{
    "company_name":"cts",
    "companyuser_id":"2",
    "date":ISODate("2020-10-16"),
    "students_appeared":"jayalakshmi,jaya,tamil,john"
},
{
    "company_name":"tcs",
    "companyuser_id":"3",
    "date":ISODate("2020-10-27"),
    "students_appeared":"vishal,ranjith,kavinraj"
},
{
    "company_name":"zoho",
    "companyuser_id":"4",
    "date":ISODate("2020-11-15"),
    "students_appeared":"praveen,naveen,kavinraj,jaya"
},
{
    "company_name":"guvi",
    "companyuser_id":"5",
    "date":ISODate("2020-11-25"),
    "students_appeared":"pavi,hari,mani,delhiraja"
}]