[{
    "topicName":"javascript_Day1",
    "month":"october",
    "task":"functions"
},
{
    "topicName":"javascript_Day2",
    "month":"october",
    "task":"for loops"
},
{
    "topicName":"javascript_Day3",
    "month":"october",
    "task":"Oops"
},
{
    "topicName":"html_Day1",
    "month":"november",
    "task":"blog about html"
},
{
    "topicName":"html_Day2",
    "month":"november",
    "task":"elements/tags"
},
{
    "topicName":"html_Day3",
    "month":"november",
    "task":"inputs"
}]